// Package admin serves the web interface that edits the configuration file.
//
// It writes the file and stops there. Applying the change is the job of the
// watcher in internal/supervisor, which notices the new file within
// general.reloadInterval seconds and hands it to the servers that are running,
// so the interface needs no hold over them at all.
//
// It has no listener and no account of its own: the HTTP file server routes
// the requests here, once it has checked that they come from a session of an
// account that sets isAdmin. Everything in this package assumes that check
// has been made.
//
// The form is not written by hand: it is generated by reflecting over
// config.Config, so a key added to the configuration appears in the browser
// with nothing else to do. See schema.go.
package admin

import (
	"bytes"
	"context"
	"crypto/rand"
	"embed"
	"encoding/base64"
	"encoding/json"
	"errors"
	"html/template"
	"io"
	"log/slog"
	"net"
	"net/http"
	"net/url"
)

//go:embed assets
var assets embed.FS

// The interface lives under the file server's go-fs query marker, the way its
// login and logout do, so that no name in the served folder is shadowed: the
// page is /?go-fs=admin, and its three endpoints are the other values.
const (
	ActionPage     = "admin"
	ActionConfig   = "admin-config"
	ActionUpload   = "admin-upload"
	ActionGenerate = "admin-generate"
)

// IsAction reports whether a marker value is one of this interface's.
func IsAction(value string) bool {
	switch value {
	case ActionPage, ActionConfig, ActionUpload, ActionGenerate:
		return true
	}
	return false
}

// marker is the query key the file server routes on.
const marker = "go-fs"

// maxPost caps the posted configuration, which is a few kilobytes of JSON.
const maxPost = 1 << 20

// Handler answers the requests the file server routes here.
type Handler struct {
	// path is the file the interface reads and writes.
	path   string
	schema Schema
	log    *slog.Logger
}

// New prepares the interface. path is the configuration file it edits.
func New(path string, logger *slog.Logger) (*Handler, error) {
	if path == "" {
		return nil, errors.New("the admin interface needs the path of the configuration file")
	}
	schema, skipped := build()
	for _, name := range skipped {
		// a shape the generated form does not handle is said out loud rather
		// than quietly left out of the page
		logger.Warn("the admin interface cannot edit this setting", "field", name)
	}
	return &Handler{path: path, schema: schema, log: logger}, nil
}

// state is what the page needs to render itself.
type state struct {
	Schema Schema         `json:"schema"`
	Values map[string]any `json:"values"`
	Path   string         `json:"path"`
	// Writable and WriteError report whether Apply can succeed at all, so that
	// a file that cannot be written says so before anything is edited.
	Writable   bool   `json:"writable"`
	WriteError string `json:"writeError,omitempty"`
	// Reload reports whether the file is watched. When it is not, a change is
	// written but only applies at the next restart, and the page says so.
	Reload bool `json:"reload"`
	// Summaries describes the values that hold key material, keyed
	// "ftps.cert", so the page shows what a base64 blob actually is.
	Summaries map[string]string `json:"summaries,omitempty"`
}

// ServeHTTP dispatches on the marker. The caller has already decided that the
// request may be here at all; what is decided here is only which endpoint it
// is for. The page is what a browser navigates to and the rest is what its
// script fetches, so a stale copy in a cache would show settings that are no
// longer there and the page carries who is signed in, which is why nothing
// here is cacheable and every answer varies on the cookie.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Add("Vary", "Cookie")
	action := r.URL.Query().Get(marker)
	get := r.Method == http.MethodGet || r.Method == http.MethodHead
	post := r.Method == http.MethodPost
	switch {
	case action == ActionPage && get:
		h.handlePage(w, r)
	case action == ActionConfig && get:
		h.handleState(w)
	case action == ActionConfig && post:
		h.handleApply(w, r)
	case action == ActionUpload && post:
		h.handleUpload(w, r)
	case action == ActionGenerate && post:
		h.handleGenerate(w, r)
	default:
		if action == ActionPage {
			w.Header().Set("Allow", "GET, HEAD")
		} else if action == ActionConfig {
			w.Header().Set("Allow", "GET, HEAD, POST")
		} else {
			w.Header().Set("Allow", "POST")
		}
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
	}
}

// pageTemplate is parsed once: a page that cannot be built is a bug in the
// embedded template rather than something a request can cause.
var pageTemplate = template.Must(template.ParseFS(assets, "assets/index.html"))

// pageStyle and pageScript are inlined into the page. They cannot be served at
// URLs of their own: every path the file server answers is a path in the
// served folder, so an asset URL would shadow a real name.
var (
	pageStyle  = template.CSS(mustRead("assets/admin.css"))
	pageScript = template.JS(mustRead("assets/admin.js"))
)

func mustRead(name string) string {
	body, err := assets.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return string(body)
}

// pageData is the page.
type pageData struct {
	// Files is the folder the page was opened from, which is where its link
	// back goes; Logout posts to the file server's logout endpoint there.
	Files  string
	Logout string
	Nonce  string
	Style  template.CSS
	Script template.JS
}

// handlePage serves the interface itself, with its style and script inlined
// under a policy that allows nothing else.
func (h *Handler) handlePage(w http.ResponseWriter, r *http.Request) {
	nonce, err := pageNonce()
	if err != nil {
		h.log.Error("the admin interface cannot render its page", "error", err)
		http.Error(w, "Server Error", http.StatusInternalServerError)
		return
	}
	var page bytes.Buffer
	err = pageTemplate.Execute(&page, pageData{
		Files:  markedURL(r.URL, ""),
		Logout: markedURL(r.URL, "logout"),
		Nonce:  nonce,
		Style:  pageStyle,
		Script: pageScript,
	})
	if err != nil {
		h.log.Error("the admin interface cannot render its page", "error", err)
		http.Error(w, "Server Error", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Content-Security-Policy", contentPolicy(nonce))
	w.WriteHeader(http.StatusOK)
	if r.Method != http.MethodHead {
		_, _ = w.Write(page.Bytes())
	}
}

// markedURL is this request's own URL with the marker set to value, or taken
// off for an empty one. The page's script asks for its endpoints relative to
// the page, so the whole interface works under whatever folder it was opened
// in.
func markedURL(u *url.URL, value string) string {
	marked := *u
	query := marked.Query()
	if value == "" {
		query.Del(marker)
	} else {
		query.Set(marker, value)
	}
	marked.RawQuery = query.Encode()
	return marked.RequestURI()
}

// pageNonce is the one-off value that lets the page's own style and script run
// under a policy that allows nothing else. The alphabet is the URL-safe one,
// which survives being written into an attribute unescaped.
func pageNonce() (string, error) {
	raw := make([]byte, 16)
	if _, err := rand.Read(raw); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(raw), nil
}

// contentPolicy closes the page off to everything it does not carry itself.
// connect-src has to stay open to this origin: the script reaches the very
// server that sent the page. The only form on it is the logout, which posts to
// this origin too, and the only image is the icon in the tab, a data URL.
func contentPolicy(nonce string) string {
	return "default-src 'none'; " +
		"style-src 'nonce-" + nonce + "'; " +
		"script-src 'nonce-" + nonce + "'; " +
		"img-src data:; " +
		"connect-src 'self'; " +
		"form-action 'self'; " +
		"base-uri 'none'"
}

func (h *Handler) handleState(w http.ResponseWriter) {
	cfg, err := h.read()
	if err != nil {
		h.log.Error("the admin interface cannot read the configuration",
			"path", h.path, "error", err)
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	values := h.schema.Values(cfg)
	body := state{
		Schema:    h.schema,
		Values:    values,
		Path:      h.path,
		Reload:    cfg.General.ReloadConfig,
		Summaries: h.schema.Summaries(values),
	}
	if err := h.writable(); err != nil {
		body.WriteError = err.Error()
	} else {
		body.Writable = true
	}
	writeJSON(w, http.StatusOK, body)
}

// handleApply validates what was posted and writes it. Nothing is applied to a
// running server here: the watcher does that when it sees the new file.
func (h *Handler) handleApply(w http.ResponseWriter, r *http.Request) {
	if !h.posted(w, r) {
		return
	}

	var posted map[string]any
	if err := json.NewDecoder(io.LimitReader(r.Body, maxPost)).Decode(&posted); err != nil {
		h.log.Info("the admin interface rejected a configuration", "reason", "the body is not JSON",
			"error", err, "address", addressOf(r))
		http.Error(w, "the body is not the configuration: "+err.Error(), http.StatusBadRequest)
		return
	}

	cfg, err := h.schema.Apply(posted)
	if err != nil {
		h.log.Info("the admin interface rejected a configuration", "reason", "a value has the wrong shape",
			"error", err, "address", addressOf(r))
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	// validated the way the file is validated when it is loaded, so that the
	// page reports what -check would report and a file that cannot work is
	// never written
	if err := cfg.Resolved().Validate(); err != nil {
		// the page shows the same message; the record is for the operator
		// who is told later that "the settings would not save"
		h.log.Info("the admin interface rejected a configuration", "reason", "it does not validate",
			"error", err, "address", addressOf(r))
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	backup, err := h.write(cfg)
	if err != nil {
		h.log.Error("the admin interface cannot write the configuration",
			"path", h.path, "error", err)
		http.Error(w, err.Error(), http.StatusConflict)
		return
	}
	h.log.Info("the configuration was written by the admin interface",
		"path", h.path, "backup", backup, "address", addressOf(r))

	writeJSON(w, http.StatusOK, map[string]any{
		"path":   h.path,
		"backup": backup,
		"reload": cfg.General.ReloadConfig,
	})
}

// posted guards everything this interface accepts a body on. A cross site form
// cannot set this content type — which is why the uploads are JSON rather than
// multipart — and a cross site fetch that sets it is stopped by a preflight
// this server does not answer. The file server has checked the origin and the
// Sec-Fetch-Site header before routing here; this is the second lock.
func (h *Handler) posted(w http.ResponseWriter, r *http.Request) bool {
	if kind := r.Header.Get("Content-Type"); kind != "application/json" {
		h.log.Debug("the admin interface refused a body that is not JSON",
			"contentType", kind, "address", addressOf(r))
		http.Error(w, "the body has to be application/json", http.StatusUnsupportedMediaType)
		return false
	}
	if origin := r.Header.Get("Origin"); origin != "" && !sameHost(origin, r.Host) {
		h.log.Warn("the admin interface refused a request from another origin",
			"origin", origin, "address", addressOf(r))
		http.Error(w, "Forbidden", http.StatusForbidden)
		return false
	}
	return true
}

// sameHost reports whether an Origin header names the host this request was
// made to. The host is compared rather than the whole origin, so that the check
// still holds when the interface is reached through something that terminates
// TLS in front of it.
func sameHost(origin, host string) bool {
	parsed, err := url.Parse(origin)
	if err != nil {
		return false
	}
	return parsed.Host == host
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

// clientKey is where the file server puts the address it resolved for a
// request, which is the client behind a trusted proxy rather than the proxy.
type clientKey struct{}

// WithClient records who a request is from, for the log lines this package
// writes. The file server calls it before handing a request over, since it is
// the one that knows which proxies to look through.
func WithClient(ctx context.Context, address string) context.Context {
	return context.WithValue(ctx, clientKey{}, address)
}

// addressOf is who a request is from: what the file server recorded, or the
// connection's own address when it recorded nothing.
func addressOf(r *http.Request) string {
	if address, ok := r.Context().Value(clientKey{}).(string); ok && address != "" {
		return address
	}
	if host, _, err := net.SplitHostPort(r.RemoteAddr); err == nil {
		return host
	}
	return r.RemoteAddr
}
